### ISSUE TITLE
Close component method

### ISSUE THREAD

**Issue by ArtemNaboka** [petr-konopelko/ng-remote-autocomplete#4] opened 2018-09-01 18:05 UTC
Calling **close** method on Autocomplete component closes the autocomplete drop-down only when items are loaded. It would be better if it closes autocomplete immediately in any state (as it was implemented in case of click outside the input).

**Comment by petro-konopelko** [comment] 2018-09-03 18:57
Can't reproduce. Could you please attach a piece of code where the problem occurs?

**Comment by petro-konopelko** [comment] 2018-11-06 19:28
Closing. If you still have a problem feel free to contact

**Closed as completed by petro-konopelko** 2018-11-06 19:28 UTC
